---
title: "Econ HW 2"
author: "Maddie Berger & Sara Orofino"
date: "4/25/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Packages

library(tidyverse)
library(janitor)
library(RColorBrewer)

#Read in data 
demand <- read_csv("Gas_Data.csv")

```


1. Find Aggregate Demand  

```{r}
# Find demand curves using linear regression:

demand_high <- lm(data = demand, price ~ qhigh)
demand_low <- lm(data = demand, price ~ qlow)

int_h <- demand_high$coefficients[1]
q_high <- abs(demand_high$coefficients[2])

int_l <- demand_low$coefficients[1]
q_low <- abs(demand_low$coefficients[2])
```

High income demand curve:  
$Price = (`r int_h`) - (`r q_high`)Q$ 

Low income demand curve:    
$Price = (`r int_l`) - (`r q_low`)Q$ 

```{r}
# Writing functions for demand:

d_high <- function(q) {
  int_h - (q_high*q)
}

d_low <- function(q) {
  int_l - (q_low*q)
}

# Demand as a function of quantity add together for aggregate demand:

d_highq <- function(p){
  (int_h/q_high) - (p/q_high)
}

d_lowq <- function(p) {
  (int_l/q_low) - (p/q_low)
}

q_sq <- d_highq(5) + d_lowq(5)

# Find the slope and intercept for the aggregate demand:
agg_int <- (int_h/q_high) + (int_l/q_low)
agg_slope <- (1/q_high) + (1/q_low)

# Write aggregate demand function as function of price:
d_aggq <- function(p) {
  agg_int - agg_slope*p
}

# Change to a function of quantity:
d_agg <- function(q) {
  (agg_int/agg_slope) - (1/agg_slope)
}

# Find mpc by plugging in 5 for the AD curve:

mpc_slope <- (5/q_sq)

mpc <- function(q) {
  mpc_slope*q
}

mec <- function(y) {
  2
}



```

Aggregate demand:        

``` {r}
#graphing the functions 

ggplot(data.frame(x=c(70000:200000)), aes(x=x)) + 
  stat_function(fun=d_high, geom ="line", color = "seagreen") + 
  stat_function(fun=d_low, geom = "line", color = "goldenrod") +
  stat_function(fun=mpc, geom = "line") +
  stat_function(fun=mec, geom = "line", color = "red") +
  stat_function(fun=d_agg, geom = "line", color = "blue")+
  labs(x = "Quantity of Gas", y = "Price")+
  scale_x_continuous(limits =c(0,500000), expand = c(0,0))+
  scale_y_continuous(limits=c(0,25), expand=c(0,0))+
  theme_bw()

```


